// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kewzscyqlkleqszcfnqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtld3pzY3lxbGtsZXFzemNmbnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDcyNDcsImV4cCI6MjA2MzMyMzI0N30.01B7zqZ3Godgjk8R53FofM8uV_YclG2wqiWXv1AqOYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);